### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by georgi-kovachev** [elsap/elsap-autoComplete#1]
Can you create a demo please?

**Comment by elsap** [comment]
Yes, this was on my to do list but I still didn't have the time to do it. Since your asking, I'm gonna prepare something here and get back to you!

Date: Sun, 16 Aug 2015 16:28:54 -0700

**Comment by georgi-kovachev** [comment]
Thanks for getting back to me.
I was trying to create but it is not working fine.

One more thing
in  line no: 51, I had to change from
elem.find('input').autocomplete to jQuery(elem).find('input').autocomplete

I am not sure what was the exact issue but using jQuery helped me.
Thanks

**Comment by elsap** [comment]
@georgi-kovachev What was the error? While doing the demo I got an error on that line and I solved with the order of the javascript's include.

```
<script src="javascripts/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.4/angular.min.js"></script>
<script src="javascripts/elsap-autocomplete.all.min.js"></script>
```
I put a demo on http://elsap.github.io/elsap-autoComplete. I didn't uploaded the code to the master branch yet, but you can see on the page's source code or I can email it to you if you prefer.

**Comment by georgi-kovachev** [comment]
Thanks so much it helps me a lot.
I was struggling to get only countries using google map autocomplete.
And I succeed it using same version of jQuery plugin, but I can't make it working with angular version.
I am having several issues such as it doesn't call google map api, and I can't specify the parameter, etc
I will upload the code, if you have a chance please take a look at it.
This is the plunker code. 
http://plnkr.co/edit/5QB0uS8Kw58jF10b125M?p=info

Thanks again

**Comment by elsap** [comment]
Can you please upload the angular version so I can look at what you maybe doing "wrong"? This plunker you uploaded is working fine here, so there isn't much I can say to help.

**Comment by georgi-kovachev** [comment]
I am using angular version 1.4.2. and when I try to convert above plunker code to angular version.

**Comment by georgi-kovachev** [comment]
Thanks for the support.

**Comment by georgi-kovachev** [comment]
hi, Elsap.
I made it work by changing some one more lines in your library
Prev:
if(typeof scope.source == 'function') {
  scope.lookup = scope.source();
}

Updated:
if(typeof scope.source == 'function') {
 scope.lookup = scope.source;
}

otherwise i couldn't recevie parameters

**Comment by georgi-kovachev** [comment]
And I found couple of issues such as ng-model is not working, and whenever I select string in the textbox I get 'onselect undefined' error, etc.

**Comment by elsap** [comment]
I really would need to see how you are doing, because I already used this in other projects and it worked fine. About the change you made... the source parameter can also be an object, you don't have to send it a function. If you send a function, you have to return the source object in it, or else it really won't work.
